###
GET localhost:245 /

### test login
GET localhost:245 /auth
Authorization: Basic {{username}} {{password}}

### register user
POST localhost:245 /user/register
Content-Type: application/json

{
  "username":"device7",
  "password":"xd"
}

### register device
POST localhost:245 /device/register
Accept: application/json

### list devices
GET localhost:245 /device/list
Accept: application/json
Authorization: Basic {{username}} {{password}}

### get device by id
GET localhost:245 /device/1
Accept: application/json
Authorization: Basic {{username}} {{password}}

### delete device by id (needs admin)
DELETE localhost:245 /device/1
Accept: application/json
Authorization: Basic {{username}} {{password}}

### get device's alerts
GET localhost:245 /device/1/alerts
Accept: application/json
Authorization: Basic {{username}} {{password}}

### get device's data
GET localhost:245 /device/1/data?limit=0
Accept: application/json
Authorization: Basic {{username}} {{password}}

### get device's config (needs admin)
GET localhost:245 /device/1/config
Accept: application/json
Authorization: Basic {{username}} {{password}}

### edit device's config (needs admin)
PUT localhost:245 /device/1/config
Content-Type: application/json
Authorization: Basic {{username}} {{password}}

{
  "frequency": 2,
  "maxTemp": 27,
  "minTemp": 15,
  "maxHumidity": 95,
  "minHumidity": 10
}

### get alerts
GET localhost:245 /alerts?limit=7
Accept: application/json
Authorization: Basic {{username}} {{password}}

### send data (as device)
POST localhost:245 /data
Content-Type: application/json
Authorization: Basic {{username}} {{password}}

{
  "temperature": 24.3,
  "humidity": 60
}

### send alert (as device)
POST localhost:245 /alert
Content-Type: application/json
Authorization: Basic {{username}} {{password}}

"essa!"

### get config (as device)
GET localhost:245 /config
Accept: application/json
Authorization: Basic {{username}} {{password}}

### change device name (needs admin)
PUT localhost:245 /device/1/name
Content-Type: application/json
Authorization: Basic {{username}} {{password}}

17

### change device location (needs admin)
PUT localhost:245 /device/1/location
Content-Type: application/json
Authorization: Basic {{username}} {{password}}

"Zespół Szkół \"Elektryk\" im. Noblistów Polskich w Słupsku"

### change user admin status (needs admin)
PUT localhost:245 /user/2/admin
Content-Type: application/json
Authorization: Basic {{username}} {{password}}

true

### delete user (needs admin)
DELETE localhost:245 /user/2
Authorization: Basic {{username}} {{password}}

### list users (needs admin)
GET localhost:245 /user/list
Accept: application/json
Authorization: Basic {{username}} {{password}}